FROM python:3.7-alpine
ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app

# pillow dependencies
RUN apk --no-cache add build-base \
                       openssl \
                       py2-pip \
                       jpeg-dev \
                       zlib-dev \
                       freetype-dev \
                       lcms2-dev \
                       openjpeg-dev \
                       tiff-dev \
                       tk-dev \
                       tcl-dev \
                       harfbuzz-dev \
                       fribidi-dev

COPY requirements.txt /app
RUN pip install -r requirements.txt
COPY . /app
