# Generated by Django 2.2 on 2019-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('bid_init_price', models.IntegerField(default=0)),
                ('bid_current_price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
