# Generated by Django 2.2 on 2019-04-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='tokopoints_deducted',
            field=models.FloatField(null=True),
        ),
    ]
